### ISSUE TITLE
[Bug] 디테일 페이지 라우팅 에러 

### ISSUE THREAD

**Issue by pangkyu** [mi-gan-zi/FE-MiGanZi#113]
문제점 
1. 메인 페이지에서 이미지 클릭해서 디테일 페이지로 넘어갈 때 제대로 라우팅 값이 안넘어옴 
  - 이미지 클릭해서 넘어갔을 때 (id 5) 
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/75983289/4e7edf98-943e-4f27-8c92-d511abdb034b)
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/75983289/21309d5a-9855-4e99-92f8-e5516596bd2a)
```ts
  const routePost = () => {
    const id = data && data[showNumber]?.id;
    navigate(`detail/${String(id)}`);
  };
```
2. 주소창에서 detail/3 등 주소값 입력 시 데이터 값 미출력 
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/75983289/14db161b-6868-44a0-acdc-767bf189a5e8)

**Comment by 0gunkim** [comment]
저도 테스트를 해봤는데 
랜덤으로 표출하네요 보여지고 안보여지고...  이상하네용
네트워크 확인해보니 요청 성공해서 데이터는 받아와지는데..

**Comment by pangkyu** [comment]
이슈 해결 완료
