### ISSUE TITLE
글쓰기 기능 버그 수정 바랍니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#135]
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/04832b62-91f8-46dd-8dcf-af495af0d807)

지도에서 지역을 검색하고 지역을 선택했는데 마커가 안찍혀서 글쓰기가 안되는 버그가 있습니다.

**Comment by 0gunkim** [comment]
카카오톡 서버 이슈가 있습니다.  마크가 안찍히면 ux적으로 표출 해야 할 것 같네요
