### ISSUE TITLE
글쓰기 두번째 버그 수정 바랍니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#136]
글쓰기 기능 동작 시 이미지 삽입 후 다음 버튼 뒤로가기 2번 하고 앞으로 가면 사진이 입력 안 된 상태로 보이는데 다시 다음 버튼을 누르면 사진이 첨부되지 않은 채 앞으로 넘어가집니다.
그리고 이미지 파일이 첨부 안 된 상태로 저장하면 서버에 등록이 실패되었다고 나오는데 계속 오른쪽 위에 버튼 글자가 저장으로 고정되어 뒤로가기를 눌러도 다음이라고 나와야 하는 버튼이 저장으로 나오고 있습니다.

**Comment by 0gunkim** [comment]
그리고 이미지 파일이 첨부 안 된 상태로 저장하면 서버에 등록이 실패되었다고 나오는데 계속 오른쪽 위에 버튼 글자가 저장으로 고정되어 뒤로가기를 눌러도 다음이라고 나와야 하는 버튼이 저장으로 나오고 있습니다.

이부분 해결
