### ISSUE TITLE
검색 기능 수정 바랍니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#138]
재하님 그 지도로 검색해서 마커를 찍은후 (마커에있는 X버튼을 누르지 않은채로) 
또다른 다른 위치를 검색하면 새로운 위치에 있는 게시물이 검색이 되지 않는데
(마커가 움직이지 않으니까 당연한 결과이긴 합니다.)
주소로 검색시 마커 위치를 초기화 시키기는 기능을 넣어야할것 같습니다. (기존 마커 제거후 다시 찍기)

**Comment by dongrri22** [comment]
수정해서 푸시했습니다!
