### ISSUE TITLE
:bug: husky 오류 

### ISSUE THREAD

**Issue by 0gunkim** [mi-gan-zi/FE-MiGanZi#24]
husky가 git hook자동화를 도와주는 프로그램인데 오류가 납니다 
정확한 오류원인을 찾지못해서 당분간 수동으로 사용하셔도되고 확장프로그램으로 깔려있는 prettier, eslint사용하시면 될듯합니다
수동 사용법은 
```json
  "format": "prettier --write --cache .",
// yarn format
  "lint": "eslint --cache ."
// yarn lint
```
아래같은 오류나 다른 오류가 있다면 
package.json에서 아래코드 삭제, node_module폴더 삭제,  후 "yarn install"하시면 됩니다 
```json
"postinstall": "husky install", //삭제
.
.
.
devDependencis:{
"husky": "^8.0.3", //삭제
```
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/116594422/4cc326ae-0aac-41c5-afdc-1bb13984f4d1)

**Comment by Goldenprevue** [comment]
husky error code 1.
https://github.com/typicode/husky/issues/1014

husky error code 127.
https://github.com/typicode/husky/issues/1038
