### ISSUE TITLE
[생성페이지] 사진업로드 할 때 랜덤으로 여러장 보내지는 현상

### ISSUE THREAD

**Issue by Goldenprevue** [mi-gan-zi/FE-MiGanZi#29]
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/116594422/751661ff-ccd7-4a94-803f-261e4b1a5829)

**Comment by new-crystal** [comment]
upload 페이지가 form으로 감싸져 있어 이벤트가 발생할 때마다 submit 이벤트가 함께 발생되는 이슈!
-> form을 div로 바꿔서 해결

**Comment by evga7** [comment]
👍👍👍👍👍
