### ISSUE TITLE
글쓰기 기능이 동작 안됩니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#45]
이슈 내용

![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/a82a9478-c247-4e5c-a518-8d56efbaa7ce)

로그인 -> 업로드 -> 이미지 선택 -> 장소 입력 설명 -> 장소 입력 순으로 했고 이후 다음 버튼 누르면 안됐습니다.

브라우저 캐시 삭제 해보고 했는데 안됐습니다.

**Comment by new-crystal** [comment]
확인 후 테스트 중입니다
