### ISSUE TITLE
url 수정 바랍니다

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#52]
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/d5eb8ca1-6e2a-4034-ad25-14c7299e515d)

// -->> / 로 수정 바랍니다

**Comment by dongrri22** [comment]
현재 올라가있는 엔드 포인트가 /로 끝나고 있나요?

**Comment by dongrri22** [comment]
수정 완료 했습니다!
