### ISSUE TITLE
근처 게시물 찾기 기능 개선 문의 드립니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#54]
현재 지도에서 근처 게시물 마커를 찍고 다른 지역을 찍고싶으면
마커를 다시 눌러서 당겨서 찍어야하는데 (저는 심지어 이렇게 되는지도 몰랐음 팡규가 말해서 알았음)
마커 찍기 버튼을 다시누르고(누르면 초기화) 지역을 다시 선택할수 있게 할순 없나요?? 있다면 수정해주시면 감사하겠습니다.

**Comment by dongrri22** [comment]
디자인 수정안 주신대로 변경하겠습니다
- 마커 생성시 마커찍기 버튼 비활성화
- 마커 삭제시 마커찍기 버튼 활성화 
![image](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44963323/4ba81254-f307-41d7-aa7c-9c889bdada4c)
