### ISSUE TITLE
husky 추가했습니다 🚀

### ISSUE THREAD

**Issue by Goldenprevue** [mi-gan-zi/FE-MiGanZi#7]
따로 설정할건 없습니다
꼭 yarn install을하고 진행해주세요

전과 다른점은
commit할 때 fomating이 이루어집니다.
그리고
push 할 때 lint검사를 하며 실패시 푸쉬가 이루어지지 않습니다.
push 할 때 lint검사를 해도 무방하지만 미리 검사하고 싶은분은 yarn lint 명령어로 에러가있는지 파악할 수 있습니다 😄

더 자세한 내용은 회의나 여유있을 때 추가 하도록하겠습니다

**Comment by pangkyu** [comment]
husky 같은 프로그램이 있는지 멕스 덕분에 배워갑니다 :D 
저도 공부하다가 프로젝트에 도움될만한 툴있으면 소개드리겠습니다👍🏽
