### ISSUE TITLE
이미지 업로드시 크롭 기능 추가 부탁드립니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#81]
![업로드이미지](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/de38d6a2-3346-424e-b27f-e55d7727de34)

현재 썸네일 이미지 및 이미지 리사이즈 작업 후 썸네일 이미지 표현 같은 경우 괜찮아졌는데

결론적으로 디자이너 님과 상의 해본 결과 이미지를 크롭 (3:4 비율로 잘라낸 후)

![Untitled](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/1aee13ac-c289-49b8-85ff-c45cdfde292d)

이렇게 3:4 범위를 정해서 업로드 하는 기능을 추가해야 할 것 같습니다.

저도 서버에서 최대한 처리해보려 생각해보고 디자이너 님과 많은 이야기를 나눠봤는데 크롭 해서 이미지를 

업로드 하는게 최선이 될 것 같습니다..

이미지 해상도 같은 경우 일단 높이 부분은 최대로 고정 해주시고 너비 부분을

(높이 * 3) / 4 == 너비 로 계산 할 수 있으므로 이 크롭 지정하는 부분을 숫자로 고정할 수 있어서 이 부분 제작해주시기 바랍니다..

![Untitled2](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/30dedcb0-daf8-45e4-84b0-bcf583be6300)![Untitled3](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/b2bbf34f-2e47-436d-aadc-eb013a28b052)

왼쪽 크롭 전 오른쪽 크롭 후

크롭 기능 이외 나왔던 아이디어
1. 

![해상도](https://github.com/mi-gan-zi/FE-MiGanZi/assets/44694917/b12892a7-8a4f-457f-90d5-f0dca9e9e96b)
이런식으로 구성

2. 본문에서 클릭하면 원본이미지가 보여진다 <-- 파일 서버 용량이 작아서 파일을 3개(원본,본문,썸네일) 저장해야 하는데 부담이 가서 불가

두 가지 모두 불가 하다고 생각해서 내린 결정입니다.

혹시 질문 있으시면 남겨주세요.

**Comment by pangkyu** [comment]
이미지 사이즈 자체가 큰 경우에 많이 잘릴거같은데 업로드 이미지 사이즈 제한이 3mb로 걸려있어서 이 부분은 생각 안하면 되는걸까요?

**Comment by evga7** [comment]
> 이미지 사이즈 자체가 큰 경우에 많이 잘릴거같은데 업로드 이미지 사이즈 제한이 3mb로 걸려있어서 이 부분은 생각 안하면 되는걸까요?

높이는 최대 값이고 그에 맞는 가로 비율만 줄어들어서 잘리는 부분이 많아지긴 하지만 용량과는 별개 입니다. 
그리고 다시 생각해보니 어차피 resize하기 때문에 업로드시 서버 용량 제한을 10mb로 높여 놓겠습니다.
실제 저장 용량은 더욱 줄어들기 때문에 3mb까지 할 필요는 없을 것 같습니다.

**Comment by Goldenprevue** [comment]
이부분 토론창에 올려놨어요 프론트분들 의견 공유 바랍니당
