### ISSUE TITLE
이미지 용량제한 3MB -> 10MB로 변경하겠습니다.

### ISSUE THREAD

**Issue by evga7** [mi-gan-zi/FE-MiGanZi#82]
사유
어차피 서버에서 resize해서 용량은 다시 줄어들기 때문에 이미지 업로드 용량은 3mb 에서 10mb 으로 변경하겠습니다.
용량 넘어가면 서버에서 이미지 용량이 초과되었습니다. 메세지 보내겠습니다.( 자세한건 개발후 백앤드 디스커션에 적어놓을게요.)

**Comment by Goldenprevue** [comment]
확인요!

**Comment by pangkyu** [comment]
완료
